### ISSUE TITLE
Crash when ostree-deploy follows ostree-commit in recipe

### ISSUE THREAD

**Issue by fdanis-oss** [go-debos/debos#148]
In case of ostree-deploy action following ostree-commit, it fails with following traces:
```
OSTree:ERROR:libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)
SIGABRT: abort
PC=0x7fa12e878e97 m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fa12e878e97
stack: frame={sp:0x7fa12636e810, fp:0x0} stack=[0x7fa125b6f090,0x7fa12636ec90)
00007fa12636e710:  0000000000000000  876100f8b7926600 
00007fa12636e720:  00007fa11c01ff30  00007fa11c085640 
00007fa12636e730:  0000000000000064  00007fa11c01ff30 
00007fa12636e740:  00007fa12636e7c0  0000000000000001 
00007fa12636e750:  0000000000000060  00007fa12ee771af 
00007fa12636e760:  000000000007f810  00007fa12636e7b8 
00007fa12636e770:  00007fa12636e790  00007fa12636e7b0 
00007fa12636e780:  00007fa11c07d7e0  876100f8b7926600 
00007fa12636e790:  0000000000000000  00007fa11c0efe58 
00007fa12636e7a0:  0000000000000000  0000000000000002 
00007fa12636e7b0:  00007fa11c0efec0  0000000000000000 
00007fa12636e7c0:  00007fa11c006130  00007fa12e85de2b 
00007fa12636e7d0:  00007fa11c085640  00007fa11c01ff30 
00007fa12636e7e0:  0000000000000000  0000000000000060 
00007fa12636e7f0:  0000000000000000  00007fa12e85c54f 
00007fa12636e800:  00007fa11c006130  00007fa12ee7742c 
00007fa12636e810: <0000000000000000  0000000000000060 
00007fa12636e820:  00007fa11c07d7e0  00007fa12eee11cc 
00007fa12636e830:  0000000000000000  00007fa12ee77724 
00007fa12636e840:  00007fa12636e8c8  00007fa12ee7797d 
00007fa12636e850:  0000000000000000  0000000000000000 
00007fa12636e860:  00007fa12636e930  0000000000000000 
00007fa12636e870:  0000008400000000  0000000000000800 
00007fa12636e880:  000000501c3b0000  0000000000000007 
00007fa12636e890:  fffffffe7fffffff  ffffffffffffffff 
00007fa12636e8a0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8b0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8c0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8d0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8e0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8f0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e900:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fa12e878e97
stack: frame={sp:0x7fa12636e810, fp:0x0} stack=[0x7fa125b6f090,0x7fa12636ec90)
00007fa12636e710:  0000000000000000  876100f8b7926600 
00007fa12636e720:  00007fa11c01ff30  00007fa11c085640 
00007fa12636e730:  0000000000000064  00007fa11c01ff30 
00007fa12636e740:  00007fa12636e7c0  0000000000000001 
00007fa12636e750:  0000000000000060  00007fa12ee771af 
00007fa12636e760:  000000000007f810  00007fa12636e7b8 
00007fa12636e770:  00007fa12636e790  00007fa12636e7b0 
00007fa12636e780:  00007fa11c07d7e0  876100f8b7926600 
00007fa12636e790:  0000000000000000  00007fa11c0efe58 
00007fa12636e7a0:  0000000000000000  0000000000000002 
00007fa12636e7b0:  00007fa11c0efec0  0000000000000000 
00007fa12636e7c0:  00007fa11c006130  00007fa12e85de2b 
00007fa12636e7d0:  00007fa11c085640  00007fa11c01ff30 
00007fa12636e7e0:  0000000000000000  0000000000000060 
00007fa12636e7f0:  0000000000000000  00007fa12e85c54f 
00007fa12636e800:  00007fa11c006130  00007fa12ee7742c 
00007fa12636e810: <0000000000000000  0000000000000060 
00007fa12636e820:  00007fa11c07d7e0  00007fa12eee11cc 
00007fa12636e830:  0000000000000000  00007fa12ee77724 
00007fa12636e840:  00007fa12636e8c8  00007fa12ee7797d 
00007fa12636e850:  0000000000000000  0000000000000000 
00007fa12636e860:  00007fa12636e930  0000000000000000 
00007fa12636e870:  0000008400000000  0000000000000800 
00007fa12636e880:  000000501c3b0000  0000000000000007 
00007fa12636e890:  fffffffe7fffffff  ffffffffffffffff 
00007fa12636e8a0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8b0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8c0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8d0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8e0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e8f0:  ffffffffffffffff  ffffffffffffffff 
00007fa12636e900:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x715d10, 0xc420125438, 0x73a4a0)
	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc420125408 sp=0xc4201253d0 pc=0x407124
github.com/sjoerdsimons/ostree-go/pkg/otbuiltin._Cfunc_ostree_sysroot_ensure_initialized(0x7fa11c3fe010, 0x0, 0xc4201384c0, 0x0)
	_cgo_gotypes.go:1657 +0x4d fp=0xc420125438 sp=0xc420125408 pc=0x694f4d
github.com/sjoerdsimons/ostree-go/pkg/otbuiltin.(*Sysroot).EnsureInitialized.func1(0x7fa11c3fe010, 0x0, 0xc4201384c0, 0xc420274720)
	/home/fdanis/src/gocode/src/github.com/sjoerdsimons/ostree-go/pkg/otbuiltin/sysroot.go:85 +0x10c fp=0xc420125470 sp=0xc420125438 pc=0x6a06bc
github.com/sjoerdsimons/ostree-go/pkg/otbuiltin.(*Sysroot).EnsureInitialized(0xc420125610, 0x0, 0x101, 0x819b00)
	/home/fdanis/src/gocode/src/github.com/sjoerdsimons/ostree-go/pkg/otbuiltin/sysroot.go:85 +0x79 fp=0xc4201254a8 sp=0xc420125470 pc=0x69ac39
github.com/sjoerdsimons/ostree-go/pkg/otbuiltin.Sysroot.InitializeFS(0xc4201384b8, 0xc42013a940, 0xd, 0xc4201e7f20, 0x1d)
	/home/fdanis/src/gocode/src/github.com/sjoerdsimons/ostree-go/pkg/otbuiltin/sysroot.go:79 +0x210 fp=0xc420125610 sp=0xc4201254a8 pc=0x69ab20
github.com/go-debos/debos/actions.(*OstreeDeployAction).Run(0xc4201460a0, 0xc4200c8580, 0x0, 0x81e600)
	/home/fdanis/src/gocode/src/github.com/go-debos/debos/actions/ostree_deploy_action.go:121 +0x151 fp=0xc4201258d0 sp=0xc420125610 pc=0x6efe41
main.do_run(0xc42013a080, 0x5, 0xc420170000, 0xe, 0xe, 0xc4200c8580, 0x0)
	/home/fdanis/src/gocode/src/github.com/go-debos/debos/cmd/debos/debos.go:32 +0xa6 fp=0xc420125968 sp=0xc4201258d0 pc=0x710506
main.main()
	/home/fdanis/src/gocode/src/github.com/go-debos/debos/cmd/debos/debos.go:412 +0xd5e fp=0xc420125f88 sp=0xc420125968 pc=0x712d5e
runtime.main()
	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc420125fe0 sp=0xc420125f88 pc=0x430952
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420125fe8 sp=0xc420125fe0 pc=0x45ac11

rax    0x0
rbx    0x7fa11c3c4010
rcx    0x7fa12e878e97
rdx    0x0
rdi    0x2
rsi    0x7fa12636e810
rbp    0x5d
rsp    0x7fa12636e810
r8     0x0
r9     0x7fa12636e810
r10    0x8
r11    0x246
r12    0x7fa12f15ede0
r13    0x7fa12636ea60
r14    0x7fa12f7e0560
r15    0x0
rip    0x7fa12e878e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Powering off.
```

**Comment by fdanis-oss** [comment]
strace of the mkdir_p_at_internal call:
```
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5715, si_uid=0, si_status=0, si_utime=3, si_stime=52} ---
rt_sigreturn({mask=[]})                 = 0
futex(0xbd7970, FUTEX_WAKE, 1)          = 1
wait4(5715, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, {ru_utime={tv_sec=0, tv_usec=31862}, ru_stime={tv_sec=0, tv_usec=525718}, ...}) = 5715
futex(0x7f2d0b71bf38, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(AT_FDCWD, "/scratch/mnt/ostree", 0xc42037a1d8, 0) = -1 ENOENT (No such file or directory)
mkdirat(AT_FDCWD, "/scratch/mnt/boot", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/dev", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/home", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/proc", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/run", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/sys", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/tmp", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/scratch/mnt/root", 0700) = -1 EEXIST (File exists)
openat(AT_FDCWD, "/scratch/mnt", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9
newfstatat(9, "ostree/repo", 0x7ffc63c7fb50, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
mkdirat(9, "ostree/repo", 0755)         = -1 ENOENT (No such file or directory)
newfstatat(9, "ostree", {st_mode=S_IFLNK|0777, st_size=15, ...}, AT_SYMLINK_NOFOLLOW) = 0
mkdirat(9, "ostree", 0755)              = -1 EEXIST (File exists)
mkdirat(9, "ostree/repo", 0755)         = -1 ENOENT (No such file or directory)
write(2, "**\nOSTree:ERROR:libglnx/glnx-shu"..., 96**
OSTree:ERROR:libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)
) = 96
```
during *ostree-deploy* after *ostree-commit* `/scratch/root/ostree` is a symbolic link to `/sysroot/ostree`, which no more exists

**Comment by obbardc** [comment]
hi @fdanis-oss 
Is this still a valid issue? are there any workarounds/further comments?

**Comment by fdanis-oss** [comment]
hi @obbardc,  
Yes this is still valid and is reproducible if previous action (`ostree-commit`) leave files/directories in rootfs.
A workaround is to add a `run` action to clean-up rootfs before calling `ostree-deploy`:
```
  # Reset the rootfs to allow to deploy OSTree from a clean rootfs
  - action: run
    description: Reset rootfs before deploying OSTree
    chroot: false
    command: find ${ROOTDIR} -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
```

**Comment by fdanis-oss** [comment]
The crash has been fixed by https://github.com/sjoerdsimons/ostree-go/pull/4.
