### ISSUE TITLE
runtime: out of memory

### ISSUE THREAD

**Issue by robertfoss** [go-debos/debos#182]
**Command**
`$ sudo docker run --rm --interactive --tty --device /dev/kvm --workdir /recipes --mount "type=bind,source=$(pwd),destination=/recipes" --security-opt label=disable godebos/debos debos.yml`

**debos.yml**
```
  - action: raw
    description: Importing Android vendor.img partition to disk image
    origin: recipe
    source: vendor_unsparse.img
    partition: vendor
    offset: 0

  - action: raw
    description: Importing Android system.img partition to disk image
    origin: recipe
    source: system_unsparse.img
    partition: system
    offset: 0

  - action: raw
    description: Importing Android userdata.img partition to disk image
    origin: recipe
    source: userdata_unsparse.img
    partition: userdata
    offset: 0
```
**Error**
```
2019/10/31 21:59:49 ==== Importing Android vendor.img partition to disk image ====
2019/10/31 21:59:52 ==== Importing Android system.img partition to disk image ====
2019/10/31 22:01:56 ==== Importing Android userdata.img partition to disk image ====
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x803d4a, 0x16)
    /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc04c000000, 0x504000000, 0xb07b58)
    /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xaee880, 0x504000000, 0x0, 0x7f37f594eb00)
    /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xaee880, 0x280001, 0x0)
    /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xaee880, 0x280001, 0xb07b68, 0x203000)
    /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xaee880, 0x280001, 0xffffffffffff0101, 0x7f37f594ebb8)
    /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
    /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xaee880, 0x280001, 0x7f37f5010101, 0x41c985)
    /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x500000200, 0x450101, 0x7f37fa4226c0)
    /usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
    /usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0xc00013ca80)
    /usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
    /usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
    /usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc000229558 sp=0xc000229550 pc=0x45b860
runtime.mallocgc(0x500000200, 0x77bc40, 0x412201, 0xc000229630)
    /usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc0002295f8 sp=0xc000229558 pc=0x412876
runtime.makeslice(0x77bc40, 0x500000200, 0x500000200, 0x8, 0x68, 0xc000012150)
    /usr/lib/go-1.11/src/runtime/slice.go:70 +0x77 fp=0xc000229628 sp=0xc0002295f8 pc=0x446e57
bytes.makeSlice(0x500000200, 0x0, 0x0, 0x0)
    /usr/lib/go-1.11/src/bytes/buffer.go:231 +0x6d fp=0xc000229668 sp=0xc000229628 pc=0x4d8e7d
bytes.(*Buffer).grow(0xc000012150, 0x500000200, 0xc0002296e8)
    /usr/lib/go-1.11/src/bytes/buffer.go:144 +0x16c fp=0xc0002296b8 sp=0xc000229668 pc=0x4d87dc
bytes.(*Buffer).Grow(0xc000012150, 0x500000200)
    /usr/lib/go-1.11/src/bytes/buffer.go:163 +0x3a fp=0xc0002296e0 sp=0xc0002296b8 pc=0x4d898a
io/ioutil.readAll(0x863680, 0xc000190018, 0x500000200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.11/src/io/ioutil/ioutil.go:34 +0x93 fp=0xc000229728 sp=0xc0002296e0 pc=0x4eb273
io/ioutil.ReadFile(0xc000452020, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.11/src/io/ioutil/ioutil.go:73 +0xd3 fp=0xc000229780 sp=0xc000229728 pc=0x4eb483
github.com/go-debos/debos/actions.(*RawAction).Run(0xc000122770, 0xc00006d230, 0x0, 0x0)
    /usr/local/go/src/github.com/go-debos/debos/actions/raw_action.go:93 +0x138 fp=0xc000229900 sp=0xc000229780 pc=0x71aa68
main.do_run(0xc000014c20, 0x5, 0xc00009afc0, 0x12, 0x12, 0xc00006d230, 0x0)
    /usr/local/go/src/github.com/go-debos/debos/cmd/debos/debos.go:31 +0x9e fp=0xc000229998 sp=0xc000229900 pc=0x73bd5e
main.main()
    /usr/local/go/src/github.com/go-debos/debos/cmd/debos/debos.go:331 +0xc91 fp=0xc000229f98 sp=0xc000229998 pc=0x73ccb1
runtime.main()
    /usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc000229fe0 sp=0xc000229f98 pc=0x432d57
runtime.goexit()
    /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000229fe8 sp=0xc000229fe0 pc=0x45d941
```
**Files**
```
$ ls -la
total 19704640
drwxr-xr-x  4 robertfoss robertfoss        4096 Oct 31 23:26  .
drwxrwxr-x 12 robertfoss robertfoss        4096 Oct 28 17:04  ..
-rw-r--r--  1 robertfoss robertfoss        4050 Oct 31 22:59  debos.yml
-rw-r--r--  1 robertfoss robertfoss  1193517056 Oct 31 22:29  system_unsparse.img
-rw-r--r--  1 robertfoss robertfoss 21474836480 Oct 31 22:45  userdata_unsparse.img
-rw-r--r--  1 robertfoss robertfoss    33832960 Oct 31 22:28  vendor_unsparse.img
```

**Comment by robertfoss** [comment]
`$ sudo docker run --rm --interactive --tty --device /dev/kvm --workdir /recipes --mount "type=bind,source=$(pwd),destination=/recipes" --security-opt label=disable godebos/debos -m 21G debos.yml` fails too, with the same error.

**Comment by sjoerdsimons** [comment]
The raw action was intended for e.g. writing the bootloader raw; I never imagined anyone writing a full disk image using it :). So the code is naieve and just does `content, err := ioutil.ReadFile(s)` which will malloc the size of the file first hence your issue.

As a workaround use a run action with dd (the `${IMAGE}` env var has the path to the device file.

But debos really should be changed to do a streaming write in these cases

**Comment by obbardc** [comment]
so the workaround would look something like:
```
  - action: run
    description: Flash rootfs.img
    command: dd if=${RECIPEDIR}/rootfs.img of=${IMAGE}-part5 bs=8M
```
where `-part5` relates to the order of the partition defined in the `image-partition` action.

Obviously this workaround looses automagically determining the destination from the partition name.

does it makes sense to check the size of the image before writing; if it's above say 16MB then use `dd` (or something else like `cat`) to copy the image?

**Comment by sjoerdsimons** [comment]
Yes; there is i think a seperate ticket to expose the various partitions in a nicer way for user to use; I don't think debos should do any extra magic to check the size and warn though, it's just as easy to fix it to do a streaming write
